<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FiltreleTestOrt</name>
   <tag></tag>
   <elementGuidId>a72d8ef9-7238-4ebc-99bc-6d1145972779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div/div/div[1]/div/div[2]/div/form/div[2]/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div/div/div[1]/div/div[2]/div/form/div[2]/div/div[3]/button</value>
   </webElementProperties>
</WebElementEntity>
