<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popupMesaji</name>
   <tag></tag>
   <elementGuidId>a2adfd26-7d51-4584-9ea8-e6a110dfbb78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ant-modal-confirm-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ant-modal-confirm-title</value>
   </webElementProperties>
</WebElementEntity>
