<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaNumarasiTest</name>
   <tag></tag>
   <elementGuidId>ae7472e6-61f1-48d3-8afa-ea69214873e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ant-pagination-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ant-pagination-item</value>
   </webElementProperties>
</WebElementEntity>
