<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaBoyutuTestDrop</name>
   <tag></tag>
   <elementGuidId>b2a54f84-8249-41db-b164-d9ed50e2f231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ant-select-item-option-content</value>
   </webElementProperties>
</WebElementEntity>
