<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablodakiDropdown</name>
   <tag></tag>
   <elementGuidId>7e796671-27bc-4773-8bb1-d6e8f385221f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div/div/div[2]/div/div/div/div/div/div/div/div/table/tbody/tr[2]/td[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div/div/div[2]/div/div/div/div/div/div/div/div/table/tbody/tr[2]/td[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
