<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablodakiDropdownAltBtnlari</name>
   <tag></tag>
   <elementGuidId>f889eed0-69af-4d81-9e84-9efee4d7a760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ant-dropdown-menu-title-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ant-dropdown-menu-title-content</value>
   </webElementProperties>
</WebElementEntity>
