<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TablodakiVerilerinTamami</name>
   <tag></tag>
   <elementGuidId>cd79a8ae-6eea-4c78-96eb-b1504dbc1e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div[1]/table/thead/tr/th[1]/div/label/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div[1]/table/thead/tr/th[1]/div/label/span/input</value>
   </webElementProperties>
</WebElementEntity>
