<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eFaturaiFrame</name>
   <tag></tag>
   <elementGuidId>50beb9c7-5539-44b1-b651-44f71dbf0043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InvoiceUploadPopUpFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InvoiceUploadPopUpFrame&quot;]</value>
   </webElementProperties>
</WebElementEntity>
