<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FaturaTipiAd</name>
   <tag></tag>
   <elementGuidId>d0e839c8-d996-4d42-8dbb-ffe9de94c308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[5]/div/div/div/div[2]/div[1]/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[5]/div/div/div/div[2]/div[1]/div/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
