<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>e-Postagonder</name>
   <tag></tag>
   <elementGuidId>a453766a-b2a6-46cd-9d74-af93e925ba0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-menu-bar-button</value>
      <webElementGuid>c20c9e46-a0b4-4ba4-9d2a-a39badd6ffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/MenuBar2</value>
      <webElementGuid>7e8f5375-2ad3-4bfa-b21d-528caffb7002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c5716de-c688-4d52-bac8-f9892c30fe36</webElementGuid>
   </webElementProperties>
</WebElementEntity>
