<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExcelAltButonlari</name>
   <tag></tag>
   <elementGuidId>b182160c-2105-49b1-8223-03f08cf746db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>vaadin-context-menu-list-box</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;overlay&quot;]/vaadin-context-menu-list-box/vaadin-context-menu-item[1]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;overlay&quot;]/vaadin-context-menu-list-box/vaadin-context-menu-item[1]/div/span</value>
   </webElementProperties>
</WebElementEntity>
