<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Excel</name>
   <tag></tag>
   <elementGuidId>b88db545-8a6d-4781-b69a-9f0c1fe28c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//vaadin-menu-bar-button[@ref_element = 'Object Repository/YeniEkranlar/Filtreler/MenuBar' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-menu-bar-button</value>
      <webElementGuid>b5a22e7c-3b80-4c70-906f-8d19f1514c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/ThemeSecondry</value>
      <webElementGuid>8fc00ae9-28c9-405a-873b-59e6f3634990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b566a9a-be6a-40de-8e78-ee9af6a1a735</webElementGuid>
   </webElementProperties>
</WebElementEntity>
