<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaBoyutuDropdown</name>
   <tag></tag>
   <elementGuidId>dc5614b9-f57c-404f-8370-1ff93e68c2a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@ref_element = 'Object Repository/YeniEkranlar/ShadowKirilimlari/SayfaBoyutu1' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0735024-d428-4472-ae2d-c8861c72b4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/SayfaBoyutu1</value>
      <webElementGuid>aa4031f5-70ac-4ee3-aca3-12dcd198de62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3572a528-e356-4c66-9833-d5b9989c9d39</webElementGuid>
   </webElementProperties>
</WebElementEntity>
