<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ÜstButon</name>
   <tag></tag>
   <elementGuidId>b58fa23f-007d-41a2-ac62-f9a776557fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//vaadin-menu-bar-button[@ref_element = 'Object Repository/YeniEkranlar/Filtreler/MenuBar' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-menu-bar-button</value>
      <webElementGuid>89d470ce-0632-4350-842f-9607f047d23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/Theme</value>
      <webElementGuid>378ad6d3-5246-4d77-b8a3-3154701b7da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fdf6fa7-89f9-4cf6-80c0-b56903cc6176</webElementGuid>
   </webElementProperties>
</WebElementEntity>
