<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuBar2</name>
   <tag></tag>
   <elementGuidId>856e0975-0023-46cd-a345-5e27f400d8c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>logo-elements-menu-bar:nth-child(2)[count(. | //*[@ref_element = 'Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot' and @ref_element_is_shadow_root = 'true']) = count(//*[@ref_element = 'Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot' and @ref_element_is_shadow_root = 'true'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>logo-elements-menu-bar:nth-child(2)</value>
      <webElementGuid>b38463a5-d4ab-4963-9690-dc3c2eafd6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot</value>
      <webElementGuid>e2704d7d-6fa6-437d-9d8f-a00ddea20675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfa647fb-2081-4da7-893e-0bba32929ea4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
