<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaNumarasiveBoyutu</name>
   <tag></tag>
   <elementGuidId>b2af5b5f-bf08-4643-8cfa-72ed91a3cd05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>logo-elements-pagination</value>
      <webElementGuid>fde6025b-25e0-43b9-acd5-862d5669d700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot</value>
      <webElementGuid>18e9314c-9c3a-4564-b503-9384aac2f7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41d9ed2b-fe0e-49cd-a17a-ff984da66372</webElementGuid>
   </webElementProperties>
</WebElementEntity>
