<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paketTürüSeciilir</name>
   <tag></tag>
   <elementGuidId>2a8fb593-70bf-4be7-89d5-39bc9450a3e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[@id='react-select-5-option-0']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@id='react-select-5-option-0']/td</value>
   </webElementProperties>
</WebElementEntity>
