<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NmrKntrlRaporYear</name>
   <tag></tag>
   <elementGuidId>647dd5de-1320-4541-baaa-450d572de5f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;txtFilterYear_DDD_L_LBI2T0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtFilterYear_DDD_L_LBI2T0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
