<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OgeSayisi</name>
   <tag></tag>
   <elementGuidId>d578a637-8266-497d-93ae-c1c8526b54de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxp-lead.dxp-summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxp-lead.dxp-summary</value>
   </webElementProperties>
</WebElementEntity>
