<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OkcIslemlerSatisTutariMax</name>
   <tag></tag>
   <elementGuidId>2d8ccd05-1ef3-493c-b3d2-e9ba88855425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;txtSalesAmountMax_I&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtSalesAmountMax_I&quot;]</value>
   </webElementProperties>
</WebElementEntity>
