<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VazgecButonu</name>
   <tag></tag>
   <elementGuidId>7d2132e9-c890-474d-8b8c-c71b87c1052a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.btn.btn-default.btn-xs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.btn.btn-default.btn-xs</value>
   </webElementProperties>
</WebElementEntity>
