<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IrsaliyeTipiMatbudan</name>
   <tag></tag>
   <elementGuidId>e560dbbb-995e-49c6-9aa3-eb187368cfc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;IrsaliyeTuru_DDD_L_LBI1T0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;IrsaliyeTuru_DDD_L_LBI1T0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
