<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MatbuIrsaliyeNo</name>
   <tag></tag>
   <elementGuidId>7c031aec-dccc-40a6-9913-d947d299c8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;txtPrintedDespacthNo_I&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtPrintedDespacthNo_I&quot;]</value>
   </webElementProperties>
</WebElementEntity>
