<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MatbuIrsaliyeTarih</name>
   <tag></tag>
   <elementGuidId>c5aff37f-997c-42cc-a10f-cb8c6e13cf76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;datePrintedDespacthDate_I&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;datePrintedDespacthDate_I&quot;]</value>
   </webElementProperties>
</WebElementEntity>
