<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eklebtn</name>
   <tag></tag>
   <elementGuidId>7dfe88ff-585a-4643-81a0-7f63b434a013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div/div/div[1]/div/div[9]/div/div/div/div[2]/div/div[1]/div[2]/div/div[2]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div/div/div[1]/div/div[9]/div/div/div/div[2]/div/div[1]/div[2]/div/div[2]/button/span[2]</value>
   </webElementProperties>
</WebElementEntity>
