<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AlıcıSec</name>
   <tag></tag>
   <elementGuidId>3b65cd23-8c03-40b9-bdbb-1fb721375c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[3]/div/div[1]/div/div[1]/div[1]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[3]/div/div[1]/div/div[1]/div[1]/div/button</value>
   </webElementProperties>
</WebElementEntity>
