<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ettn</name>
   <tag></tag>
   <elementGuidId>dc558b12-993d-479e-88c1-72059bfeb88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div/div/div/div/div[1]/div/div[2]/div/form/div[1]/div[13]/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div/div/div/div/div[1]/div/div[2]/div/form/div[1]/div[13]/div/div[2]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
