<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SecBtn</name>
   <tag></tag>
   <elementGuidId>7a5b8854-32e2-42bd-af64-2e053b79c2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[2]/div/div[2]/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[2]/div/div[2]/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
