<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eArsivVergiDahilTutar</name>
   <tag></tag>
   <elementGuidId>b8df6722-f915-4f1a-a564-83effc176a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewEArchiveInvoices_tccell0_7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewEArchiveInvoices_tccell0_7&quot;]</value>
   </webElementProperties>
</WebElementEntity>
