<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eFaturaYanıt</name>
   <tag></tag>
   <elementGuidId>d70a9b00-6f8a-4a50-a440-ed21fe42a3aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewPostboxIncomingApplicationResponses_tccell0_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewPostboxIncomingApplicationResponses_tccell0_4&quot;]</value>
   </webElementProperties>
</WebElementEntity>
