<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eIrsaliyeToplamTutar</name>
   <tag></tag>
   <elementGuidId>bdfa198a-5343-4e34-9028-44067349d1c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewDespatchAdvice_tccell0_5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewDespatchAdvice_tccell0_5&quot;]</value>
   </webElementProperties>
</WebElementEntity>
