<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eSMMToplamTutar</name>
   <tag></tag>
   <elementGuidId>ca41c7b4-60fa-4fea-a190-c420b6c5dd55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewSEReceipt_tccell0_8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewSEReceipt_tccell0_8&quot;]</value>
   </webElementProperties>
</WebElementEntity>
