<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerininArtiButonu</name>
   <tag></tag>
   <elementGuidId>9f72dbb8-26e5-4774-85b7-a29ae64e4308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>ancestor::tr[1]//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>ancestor::tr[1]//img</value>
   </webElementProperties>
</WebElementEntity>
