<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ZarfaGitGiden</name>
   <tag></tag>
   <elementGuidId>b70dd6a5-699a-4fed-88a0-0ee5c43ac9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewSubEnvelope44000003078_tccell0_0&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewSubEnvelope44000003078_tccell0_0&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
