<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ZarfaGitGelenZarf</name>
   <tag></tag>
   <elementGuidId>731f2408-b78d-4dbd-b966-e557c00da533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;GridViewSubEnvelope116111884_tccell0_0&quot;]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewSubEnvelope44000004058_tccell0_0&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewSubEnvelope44000004058_tccell0_0&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
