<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>e-SaklamaSekmeBasligi</name>
   <tag></tag>
   <elementGuidId>5e9c7218-e7dd-42da-b17a-e390cc256e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;StorageUploadsError&quot;]/div/div/div[1]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;StorageUploadsError&quot;]/div/div/div[1]/h4</value>
   </webElementProperties>
</WebElementEntity>
