<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SekmeKapama</name>
   <tag></tag>
   <elementGuidId>284fccc4-bcae-42b6-8b40-2442ed7fa724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;StorageUploadsError&quot;]/div/div/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;StorageUploadsError&quot;]/div/div/div[1]/button</value>
   </webElementProperties>
</WebElementEntity>
