<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UlkeAdi</name>
   <tag></tag>
   <elementGuidId>2ce0af4b-5c06-4d53-8372-5ac47e927a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ant-select-item-option-content</value>
   </webElementProperties>
</WebElementEntity>
