<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropdownNumaraKntrl</name>
   <tag></tag>
   <elementGuidId>a12389a5-3a9e-4e4f-9576-36511ff06b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewMissingElements_DXPagerBottom_DDB&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewMissingElements_DXPagerBottom_DDB&quot;]</value>
   </webElementProperties>
</WebElementEntity>
