<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KydtBtnIrsaliyeYanit</name>
   <tag></tag>
   <elementGuidId>2773c3ff-8d34-4718-933d-d1ef24ec0c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btnSave_CD&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSave_CD&quot;]/span</value>
   </webElementProperties>
</WebElementEntity>
