<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParametreButonlari</name>
   <tag></tag>
   <elementGuidId>45407a8e-cf60-4e92-87ea-38082a417ab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.btn.btn-link.accordion-title.border-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.btn.btn-link.accordion-title.border-0</value>
   </webElementProperties>
</WebElementEntity>
