<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaNumarasi</name>
   <tag></tag>
   <elementGuidId>531ca815-2bdd-4541-9cc2-2c127d22acbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxp-num</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxp-num</value>
   </webElementProperties>
</WebElementEntity>
