<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaBoyutuDropdown</name>
   <tag></tag>
   <elementGuidId>b61376db-9a8c-4193-b5be-a5ef836ef8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GridViewEArchiveFileOperations_DXPagerBottom_DDB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GridViewEArchiveFileOperations_DXPagerBottom_DDB</value>
   </webElementProperties>
</WebElementEntity>
