<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SayfaBoyutuRprlrTopluVeriIndir</name>
   <tag></tag>
   <elementGuidId>fcce8ead-1a95-44a6-b529-a2be1fc26d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;GridViewFiles_DXPagerBottom_PSB&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;GridViewFiles_DXPagerBottom_PSB&quot;]</value>
   </webElementProperties>
</WebElementEntity>
