<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SonrakiSayfa</name>
   <tag></tag>
   <elementGuidId>0b774964-8eff-4197-b06a-758e9fde34d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxWeb_pNext_LECustomTheme</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxWeb_pNext_LECustomTheme</value>
   </webElementProperties>
</WebElementEntity>
