<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SonSayfa</name>
   <tag></tag>
   <elementGuidId>e0b69e08-b1ea-49ef-9f62-c5610c2e4589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxWeb_pLast_LECustomTheme</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxWeb_pLast_LECustomTheme</value>
   </webElementProperties>
</WebElementEntity>
