<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webAdresi</name>
   <tag></tag>
   <elementGuidId>845def3e-4dbf-473a-8538-e0903ca1c7b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[1]/div/div[6]/div/div/div/div[2]/div/form/div/div[4]/div/div[2]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[1]/div/div[6]/div/div/div/div[2]/div/form/div/div[4]/div/div[2]/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
